export const desktopMenus = [{
  name:'login',
  text:'浏览器',
  icon:'../../../static/img/icon32/browser_32.png',
  top:'',
  left:''
},{
  name:'home',
  text:'我的任务',
  icon:'../../../static/img/icon32/task_32.png',
  top:'',
  left:''
}]

export const contextMenus = [{
  text:'主题风格',
  iconCls:'icon-color',
  children:[{
    value:'sunny',
    text:'sunny',
    iconCls:'icon-color'
  },{
    value:'pepper-grinder',
    text:'pepper-grinder',
    iconCls:'icon-color'
  },{
    value:'dark-hive',
    text:'dark-hive',
    iconCls:'icon-color'
  },{
    value:'cupertino',
    text:'cupertino',
    iconCls:'icon-color'
  },{
    value:'metro-red',
    text:'metro-red',
    iconCls:'icon-color'
  },{
    value:'metro-orange',
    text:'metro-orange',
    iconCls:'icon-color'
  },{
    value:'metro-green',
    text:'metro-green',
    iconCls:'icon-color'
  },{
    value:'metro-gray',
    text:'metro-gray',
    iconCls:'icon-color'
  },{
    value:'metro-blue',
    text:'metro-blue',
    iconCls:'icon-color'
  }]
},{
  text:'自动排序',
  iconCls:'icon-sort',
  children:[{
    value:'按名称升序',
    text:'按名称升序',
    iconCls:'icon-sort-name-asc'
  },{
    value:'按名称降序',
    text:'按名称降序',
    iconCls:'icon-sort-name-desc'
  },{
    value:'按时间升序',
    text:'按时间升序',
    iconCls:'icon-sort-time-asc'
  },{
    value:'按时间降序',
    text:'按时间降序',
    iconCls:'icon-sort-time-desc'
  }]
},{
  value:'显示桌面',
  text:'显示桌面',
  iconCls:'icon-desktop'
},{
  value:'锁定屏幕',
  text:'锁定屏幕',
  iconCls:'icon-lock',
},{
  value:'个人设置',
  text:'个人设置',
  iconCls:'icon-config',
},{
  value:'办公模式',
  text:'办公模式',
  iconCls:'icon-work',
},{
  value:'全屏显示',
  text:'全屏显示',
  iconCls:'icon-fullscreen',
}]

export const startMenus = [{
  group:'我的工作区',
  items:[{
    name:'我的门户',
    icon:'',
    url:''
  },{
    name:'我的任务',
    icon:'',
    url:''
  },{
    name:'已办任务',
    icon:'',
    url:''
  },{
    name:'消息提醒',
    icon:'',
    url:''
  },{
    name:'个人设置',
    icon:'',
    url:''
  },{
    name:'日程计划',
    icon:'',
    url:''
  },{
    name:'意见箱',
    icon:'',
    url:''
  },{
    name:'系统公告',
    icon:'',
    url:''
  }]
},{
  group:'系统设置',
  items:[{
    name:'流程列表',
    icon:'',
    url:''
  },{
    name:'表单列表',
    icon:'',
    url:''
  },{
    name:'校验规则列表',
    icon:'',
    url:''
  },{
    name:'用户列表',
    icon:'',
    url:''
  },{
    name:'角色列表',
    icon:'',
    url:''
  },{
    name:'菜单列表',
    icon:'',
    url:''
  },]
},{
  group:'其他',
  items:[{
    name:'使用帮助',
    icon:'',
    url:''
  }]
}]

export const funcs = [{
  name:'全屏',
  icon:'fa-user',
  url:''
},{
  name:'办公模式',
  icon:'fa-user',
  url:''
},{
  name:'个人设置',
  icon:'fa-user',
  url:''
},{
  name:'注销',
  icon:'fa-user',
  url:''
}]