export const layout = [{
  type:'container',
  name:'LxtFlex',
  label:'栅格布局',
  column:[12,12],
  width:'100%',
  height:'100px',
  icon:'fa-columns'
},{
  type:'container',
  name:'LxtPanel',
  label:'面板',
  title:'标题',
  width:'100%',
  height:'50px',
  icon:'fa-window-maximize'
}]

export const form = [{
  type:'field',
  name:'LxtInput',
  label:'文本框',
  title:'字段',
  width:'100%',
  height:'50px',
  icon:'fa-edit'
},{
  type:'field',
  name:'LxtInput',
  label:'下拉框',
  title:'字段',
  width:'100%',
  height:'50px',
  icon:'fa-toggle-down'
},{
  type:'field',
  name:'LxtInput',
  label:'日期',
  title:'字段',
  width:'100%',
  height:'50px',
  icon:'fa-calendar-o'
},{
  type:'field',
  name:'LxtInput',
  label:'复选框',
  title:'字段',
  width:'100%',
  height:'50px',
  icon:'fa-check-square-o'
},{
  type:'field',
  name:'LxtInput',
  label:'单选框',
  title:'字段',
  width:'100%',
  height:'50px',
  icon:'fa-dot-circle-o'
},{
  type:'field',
  name:'LxtInput',
  label:'开关',
  title:'字段',
  width:'100%',
  height:'50px',
  icon:'fa-toggle-on'
}]

export const display = [{
  type:'block',
  name:'LxtImage',
  label:'图片',
  title:'标题',
  width:'100%',
  height:'50px',
  icon:'fa-image'
}]